from setuptools import setup, find_packages
import os


# Read the README file
def read_readme():
    readme_path = os.path.join(os.path.dirname(__file__), "README.md")
    if os.path.exists(readme_path):
        with open(readme_path, "r", encoding="utf-8") as f:
            return f.read()
    return ""


setup(
    name="lemmo-apps",
    version="1.0.0",
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        "Django>=5.0.0",
        "djangorestframework>=3.14.0",
        "django-cors-headers>=4.0.0",
        "graphene-django>=3.1.0",
        "graphql-core>=3.2.0",
        "psycopg2-binary>=2.9.0",
        "django-mptt>=0.14.0",
        "django-simple-history>=3.3.0",
        "Pillow>=9.5.0",
        "django-phonenumber-field>=7.3.0",
        "phonenumbers>=8.13.0",
        "python-dateutil>=2.8.0",
        "django-filter>=23.0",
        "django-environ>=0.11.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.0",
            "pytest-django>=4.5.0",
            "factory-boy>=3.3.0",
            "coverage>=7.2.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "isort>=5.12.0",
            "pre-commit>=3.3.0",
            "django-debug-toolbar>=4.0.0",
        ],
        "production": [
            "gunicorn>=20.1.0",
            "whitenoise>=6.5.0",
            "redis>=4.5.0",
            "django-redis>=5.2.0",
            "celery>=5.3.0",
            "django-celery-beat>=2.5.0",
            "django-celery-results>=2.5.0",
            "sentry-sdk>=1.25.0",
        ],
        "healthcare": [
            "fhirclient>=3.2.0",
            "hl7>=0.4.4",
            "pandas>=2.0.0",
            "numpy>=1.24.0",
            "openpyxl>=3.1.0",
        ],
        "full": [
            "django-allauth>=0.54.0",
            "django-oauth-toolkit>=2.2.0",
            "django-storages>=1.13.0",
            "django-reversion>=6.0.0",
            "drf-yasg>=1.21.0",
            "python-decouple>=3.8",
            "django-anymail>=10.0",
            "twilio>=8.0.0",
            "django-geoposition>=0.3.0",
            "geopy>=2.3.0",
            "reportlab>=4.0.0",
            "WeasyPrint>=59.0",
            "django-ratelimit>=4.0.0",
            "django-haystack>=3.2.0",
            "elasticsearch>=8.8.0",
            "django-health-check>=3.16.0",
            "django-extensions>=3.2.0",
        ],
    },
    author="2MCorp",
    author_email="contact@2mcorp.com",
    description="A comprehensive Django-based backend system for healthcare logistics and supply chain management",
    long_description=read_readme(),
    long_description_content_type="text/markdown",
    url="https://github.com/2mcorp/lemmo-apps",
    project_urls={
        "Bug Reports": "https://github.com/2mcorp/lemmo-apps/issues",
        "Source": "https://github.com/2mcorp/lemmo-apps",
        "Documentation": "https://lemmo-apps.readthedocs.io/",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Healthcare Industry",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Framework :: Django",
        "Framework :: Django :: 4.2",
        "Topic :: Office/Business",
        "Topic :: Office/Business :: Financial",
        "Topic :: Office/Business :: Financial :: Accounting",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: System :: Systems Administration",
        "Topic :: Utilities",
    ],
    keywords=[
        "healthcare",
        "logistics",
        "supply-chain",
        "inventory",
        "pharmacy",
        "hospital",
        "medical",
        "django",
        "graphql",
        "api",
        "management",
        "tracking",
        "compliance",
        "fda",
        "dea",
        "hipaa",
    ],
    python_requires=">=3.8",
    entry_points={
        "console_scripts": [
            "lemmo-admin=lemmo_apps.management:main",
        ],
    },
    package_data={
        "lemmo_apps": [
            "templates/**/*",
            "static/**/*",
            "migrations/**/*",
        ],
    },
    zip_safe=False,
)
