from django.urls import path
from . import views

app_name = "supplier"

urlpatterns = [
    # Supplier URLs
    path("suppliers/", views.SupplierListView.as_view(), name="supplier-list"),
    path(
        "suppliers/<uuid:pk>/",
        views.SupplierDetailView.as_view(),
        name="supplier-detail",
    ),
    path(
        "suppliers/create/", views.SupplierCreateView.as_view(), name="supplier-create"
    ),
    path(
        "suppliers/<uuid:pk>/update/",
        views.SupplierUpdateView.as_view(),
        name="supplier-update",
    ),
    path(
        "suppliers/<uuid:pk>/delete/",
        views.SupplierDeleteView.as_view(),
        name="supplier-delete",
    ),
    path(
        "suppliers/<uuid:pk>/activate/",
        views.SupplierActivateView.as_view(),
        name="supplier-activate",
    ),
    path(
        "suppliers/<uuid:pk>/deactivate/",
        views.SupplierDeactivateView.as_view(),
        name="supplier-deactivate",
    ),
    # Supplier Contacts
    path(
        "suppliers/<uuid:supplier_id>/contacts/",
        views.SupplierContactListView.as_view(),
        name="supplier-contacts",
    ),
    path(
        "contacts/<uuid:pk>/",
        views.SupplierContactDetailView.as_view(),
        name="contact-detail",
    ),
    path(
        "contacts/create/",
        views.SupplierContactCreateView.as_view(),
        name="contact-create",
    ),
    path(
        "contacts/<uuid:pk>/update/",
        views.SupplierContactUpdateView.as_view(),
        name="contact-update",
    ),
    path(
        "contacts/<uuid:pk>/delete/",
        views.SupplierContactDeleteView.as_view(),
        name="contact-delete",
    ),
    # Supplier Ratings
    path(
        "suppliers/<uuid:supplier_id>/ratings/",
        views.SupplierRatingListView.as_view(),
        name="supplier-ratings",
    ),
    path(
        "ratings/<uuid:pk>/",
        views.SupplierRatingDetailView.as_view(),
        name="rating-detail",
    ),
    path(
        "ratings/create/",
        views.SupplierRatingCreateView.as_view(),
        name="rating-create",
    ),
    path(
        "ratings/<uuid:pk>/update/",
        views.SupplierRatingUpdateView.as_view(),
        name="rating-update",
    ),
    path(
        "ratings/<uuid:pk>/delete/",
        views.SupplierRatingDeleteView.as_view(),
        name="rating-delete",
    ),
    # Purchase Orders
    path(
        "purchase-orders/",
        views.PurchaseOrderListView.as_view(),
        name="purchase-order-list",
    ),
    path(
        "purchase-orders/<uuid:pk>/",
        views.PurchaseOrderDetailView.as_view(),
        name="purchase-order-detail",
    ),
    path(
        "purchase-orders/create/",
        views.PurchaseOrderCreateView.as_view(),
        name="purchase-order-create",
    ),
    path(
        "purchase-orders/<uuid:pk>/update/",
        views.PurchaseOrderUpdateView.as_view(),
        name="purchase-order-update",
    ),
    path(
        "purchase-orders/<uuid:pk>/delete/",
        views.PurchaseOrderDeleteView.as_view(),
        name="purchase-order-delete",
    ),
    path(
        "purchase-orders/<uuid:pk>/approve/",
        views.PurchaseOrderApproveView.as_view(),
        name="purchase-order-approve",
    ),
    path(
        "purchase-orders/<uuid:pk>/reject/",
        views.PurchaseOrderRejectView.as_view(),
        name="purchase-order-reject",
    ),
    path(
        "purchase-orders/<uuid:pk>/order/",
        views.PurchaseOrderOrderView.as_view(),
        name="purchase-order-order",
    ),
    path(
        "purchase-orders/<uuid:pk>/receive/",
        views.PurchaseOrderReceiveView.as_view(),
        name="purchase-order-receive",
    ),
    # Purchase Order Items
    path(
        "purchase-orders/<uuid:po_id>/items/",
        views.PurchaseOrderItemListView.as_view(),
        name="purchase-order-items",
    ),
    path(
        "purchase-order-items/<uuid:pk>/",
        views.PurchaseOrderItemDetailView.as_view(),
        name="purchase-order-item-detail",
    ),
    path(
        "purchase-order-items/create/",
        views.PurchaseOrderItemCreateView.as_view(),
        name="purchase-order-item-create",
    ),
    path(
        "purchase-order-items/<uuid:pk>/update/",
        views.PurchaseOrderItemUpdateView.as_view(),
        name="purchase-order-item-update",
    ),
    path(
        "purchase-order-items/<uuid:pk>/delete/",
        views.PurchaseOrderItemDeleteView.as_view(),
        name="purchase-order-item-delete",
    ),
    # Contracts
    path("contracts/", views.ContractListView.as_view(), name="contract-list"),
    path(
        "contracts/<uuid:pk>/",
        views.ContractDetailView.as_view(),
        name="contract-detail",
    ),
    path(
        "contracts/create/", views.ContractCreateView.as_view(), name="contract-create"
    ),
    path(
        "contracts/<uuid:pk>/update/",
        views.ContractUpdateView.as_view(),
        name="contract-update",
    ),
    path(
        "contracts/<uuid:pk>/delete/",
        views.ContractDeleteView.as_view(),
        name="contract-delete",
    ),
    path(
        "contracts/<uuid:pk>/activate/",
        views.ContractActivateView.as_view(),
        name="contract-activate",
    ),
    path(
        "contracts/<uuid:pk>/terminate/",
        views.ContractTerminateView.as_view(),
        name="contract-terminate",
    ),
    # Contract Terms
    path(
        "contracts/<uuid:contract_id>/terms/",
        views.ContractTermListView.as_view(),
        name="contract-terms",
    ),
    path(
        "contract-terms/<uuid:pk>/",
        views.ContractTermDetailView.as_view(),
        name="contract-term-detail",
    ),
    path(
        "contract-terms/create/",
        views.ContractTermCreateView.as_view(),
        name="contract-term-create",
    ),
    path(
        "contract-terms/<uuid:pk>/update/",
        views.ContractTermUpdateView.as_view(),
        name="contract-term-update",
    ),
    path(
        "contract-terms/<uuid:pk>/delete/",
        views.ContractTermDeleteView.as_view(),
        name="contract-term-delete",
    ),
    # Healthcare specific URLs
    path(
        "approved-suppliers/",
        views.ApprovedSuppliersView.as_view(),
        name="approved-suppliers",
    ),
    path(
        "preferred-suppliers/",
        views.PreferredSuppliersView.as_view(),
        name="preferred-suppliers",
    ),
    path(
        "active-contracts/",
        views.ActiveContractsView.as_view(),
        name="active-contracts",
    ),
    path(
        "expiring-contracts/",
        views.ExpiringContractsView.as_view(),
        name="expiring-contracts",
    ),
    path("pending-orders/", views.PendingOrdersView.as_view(), name="pending-orders"),
    # Analytics URLs
    path("supplier-stats/", views.SupplierStatsView.as_view(), name="supplier-stats"),
    path(
        "procurement-stats/",
        views.ProcurementStatsView.as_view(),
        name="procurement-stats",
    ),
]
